### ISSUE TITLE
Fix RSS links in main RSS file

### ISSUE THREAD

**Issue by SiegfriedEhret** [0gust1/personal#2]
You have `/posts` and `/logs`, but in your main RSS feed everything goes under `/posts` (see https://github.com/0gust1/personal/blob/main/src/routes/rss.xml/%2Bserver.ts#L13), so in the current we have this:

```xml
<item>
  <guid>https://0gust1.neocities.org/posts/2023-05-09_links</guid>
  <title>Links and notes from may 2023</title>
  <description>undefined</description>
  <link>https://0gust1.neocities.org/posts/2023-05-09_links</link>
  <pubDate>Tue, 09 May 2023 00:00:00 GMT</pubDate>
</item>
```

But the correct link is https://0gust1.neocities.org/logs/2023-05-09_links

**Comment by 0gust1** [comment]
fixed by #4
