### ISSUE TITLE
Add full link to items in the RSS

### ISSUE THREAD

**Issue by SiegfriedEhret** [0gust1/personal#6]
Coucou !

Currently in https://0gust1.neocities.org/rss.xml each `item` contains the following:

```xml
<link>/logs/2023-07-01_glsl}</link>
```

In my RSS app, clicking on the item does not open the website. It would if the full url was present in the link.

For example: https://www.theverge.com/rss/index.xml

**Comment by 0gust1** [comment]
Ah, the shame of this pesky `}`...

Beside this typo, I'll check the specs but as far as remember, relative URLs should be usable, as soon as the `<link>` of the `<channel>` is correct. 

Next time, I'll do:
- https://www.rssboard.org/rss-validator/
- https://validator.w3.org/feed/

Thanks a lot (and sorry!)

**Comment by 0gust1** [comment]
Erf
![Capture d’écran 2023-07-06 à 17 34 09](https://github.com/0gust1/personal/assets/578154/b840257e-8df7-42bc-9047-814863880fd9)

**Comment by 0gust1** [comment]
should be good, fixed by #7 (I checked on the W3C validator).

THANKS!
